version: '3'

services:
  #mongo:
  #  image: 'mongo:latest'
  #  container_name: 'mongo'
  #  ports:
  #    - '27100:27017'

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'